import pygame as pg
from typing import Protocol

class AbstractScene(Protocol):
    def __init__(self, game) -> None: ...
    def draw(self, surf: pg.Surface) -> list[pg.FRect | pg.Rect]: ...
    def update(self, *args, **kwargs) -> None: ...